services:
  - type: web
    name: flask-web-app
    env: python
    region: singapore
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: REDDIT_CLIENT_ID
        value: YOUR_CLIENT_ID
      - key: REDDIT_CLIENT_SECRET
        value: YOUR_CLIENT_SECRET
      - key: REDDIT_USER_AGENT
        value: YOUR_USER_AGENT
